branch-defaults:
  master:
    environment: photofolio-env
global:
  application_name: photofolio
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
